apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-deployment
  labels:
    app: giropops-senhas
spec:
  replicas: {{ .Values.giropops.replicaCount }}
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: "{{ .Values.giropops.image.repository }}:{{ .Values.giropops.image.tag }}"
        imagePullPolicy: {{ .Values.giropops.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.giropops.service.port }}
        env:
        - name: REDIS_HOST
          value: {{ .Values.giropops.env.REDIS_HOST }}
        resources:
          {{- toYaml .Values.giropops.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.giropops.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.giropops.readinessProbe | nindent 10 }}
