apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: giropops-senhas  
  namespaceSelector:
    matchNames:
      - giropops-senhas  
  endpoints:
  - port: http  
    path: /metrics 
    interval: 30s
