services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - app-net
    restart: always
    volumes:
      - .:/app
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-net
    restart: always
networks:
  app-net:
    driver: bridge
