# Giropops Application
giropops:
  replicaCount: 1
  image:
    repository: rafallltm/giropops-senhas
    tag: v6-dev
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 5000
  env:
    REDIS_HOST: redis-service
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  livenessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Redis
redis:
  replicaCount: 1
  image:
    repository: redis
    tag: alpine3.19
  service:
    type: ClusterIP
    port: 6379
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

# Namespace
namespace: nxzero
