apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-deployment
  namespace: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: rafallltm/giropops-senhas:v6-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        resources:
          requests:
            cpu: 250m  
            memory: 64Mi
          limits:
            cpu: 500m 
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
