apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: giropops-senhas
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine3.19
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
